local foil_back = SMODS.Back{
    key = "foil_everything",
    loc_txt = {
        name = "Foil Everything",
        text = {
            "All future cards generated by the run",
            "appear as {C:edition}Foil{}."
        }
    },
    atlas = "centers",
    pos = { x = 0, y = 0 },
    config = {},
    unlocked = true,
    discovered = true,
}

-- This is called whenever the deck's effect is checked
function foil_back:calculate(back, context)
    -- context.card is the card being created in most generation contexts
    local card = context and context.card
    if not card then return end

    -- Only touch cards that don't already have an edition
    if card.edition then return end

    -- Limit to “upcoming” cards (shop, packs, etc.)
    -- You can add/remove contexts as you like.
    if context.context == "shop_joker"
        or context.context == "shop_card"
        or context.context == "booster_reward"
        or context.context == "tag_reward"
        or context.context == "planet_pack"
        or context.context == "tarot_pack"
    then
        card:set_edition("e_foil", true)
    end
end

return foil_back